name: Kubernets

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - run: git clone https://github.com/leollo98/Infra_CI_Kubernetes.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    # Analisa todos os arquivos presentes no diretório em que está sendo executado, baixa todas as bibliotecas (que são conhecidas como módulos), e inicia os arquivos de configuração necessários.
    - run: terraform -chdir=Infra_CI_Kubernets/env/Homolog init

    - run: terraform -chdir=Infra_CI_Kubernets/env/Homolog apply -auto-approve
 
